services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentor-ia-api
    ports:
      - "10000:10000"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:10000

      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}

      OpenRouter__ApiKey: ${OpenRouter__ApiKey}
      OpenRouter__BaseUrl: ${OpenRouter__BaseUrl}
      OpenRouter__Model: ${OpenRouter__Model}

      Jwt__Key: ${Jwt__Key}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
      Jwt__DurationInMinutes: ${Jwt__DurationInMinutes}